[host]
os = "-"
uptime = "-"
host = "-"
kernel = "-"
ide = "-"

[languages]
secondary = "-"
native = "-"

[skills]
softskill = "-"
hardskill = "-"

[contact]
linkedIn = "-"
discord = "-"

[contact.email]
personal = "-"
work = "-"
