[host]
os     = "NixOS 26.11 (Zokor) x86_64"
uptime = "01/08/2023" # format: dd/mm/yyyy 
host   = "Cyber Asia, University"
kernel = "DE/DL Informatics / Computer Science"
ide    = "Zed 1.9.0 (GUI), Helix 25.07.1 (TUI)"

[languages]
secondary = "English, Arabic (Boarding)"
native    = "Indonesian"

[skills]
softskill = "Figma, Canva"
hardskill = "Overclocking, Undervolting"

[contact]
linkedIn = "msalmanrafadhlih"
discord  = "tquilla(dot)"

[contact.email]
personal  = "tquilla@proton.me"
work = "contact.me@msalmanrafadhlih.dev"
